# Generated by Django 3.1.1 on 2020-09-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
