# Generated by Django 3.1.1 on 2020-09-26 05:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20200926_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание точки'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=100, verbose_name='Идентификатор точки'),
        ),
        migrations.AlterField(
            model_name='place',
            name='point_title',
            field=models.CharField(max_length=100, verbose_name='Название точки'),
        ),
    ]
