# Generated by Django 3.1.1 on 2020-09-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20200930_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='point_title',
            field=models.CharField(help_text='При наведении курсором на точку будет отображаться это название.', max_length=100, verbose_name='Название точки'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(help_text='Название точки в карточке.', max_length=100, verbose_name='Название'),
        ),
    ]
